[build-system]
requires = ["setuptools>=61.0"]
build-backend = "setuptools.build_meta"

[project]
name = "apigen"
version = "1.0.3"
authors = [
  { name="Ram Suthar", email="ramsuthar305@gmail.com" },
]
description = "A Django API toolkit for response utilities, exceptions, middleware, and alert handlers - Open source version of Skillspe's Hephaestus package"
readme = "README.md"
requires-python = ">=3.7"

classifiers = [
    "Programming Language :: Python :: 3",
    "License :: OSI Approved :: MIT License",
    "Operating System :: OS Independent",
    "Framework :: Django",
    "Intended Audience :: Developers",
    "Topic :: Software Development :: Libraries :: Python Modules",
    "Topic :: Internet :: WWW/HTTP",
]
keywords = [
    "django",
    "api",
    "response",
    "exceptions",
    "middleware",
    "alerts",
    "toolkit",
    "utilities",
    "hephaestus",
]

[project.urls]
"Homepage" = "https://github.com/ramsuthar305/apigen"
"Bug Tracker" = "https://github.com/ramsuthar305/apigen/issues"
"Source Code" = "https://github.com/ramsuthar305/apigen"